name: Documentation

on:
  push:
    branches: [ main ]
    paths:
      - 'docs/**'
      - 'README.md'
      - 'CONTRIBUTING.md'
      - 'knowledge_bases/examples/**'

jobs:
  build-docs:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install documentation dependencies
      run: |
        pip install mkdocs mkdocs-material mkdocs-mermaid2-plugin
    
    - name: Build documentation
      run: |
        # Create mkdocs.yml if it doesn't exist
        if [ ! -f mkdocs.yml ]; then
          cat > mkdocs.yml << EOF
        site_name: JeweledTech Agentic Framework
        site_url: https://jeweledtech.github.io/agentic-framework/
        repo_url: https://github.com/jeweledtech/agentic-framework
        repo_name: jeweledtech/agentic-framework
        
        theme:
          name: material
          features:
            - navigation.sections
            - navigation.expand
            - navigation.top
            - search.highlight
            - content.code.copy
          palette:
            - scheme: default
              primary: indigo
              accent: indigo
        
        nav:
          - Home: README.md
          - Getting Started: docs/getting-started.md
          - Agent Development: knowledge_bases/examples/agent_development_guide.md
          - Framework Overview: knowledge_bases/examples/framework_overview.md
          - Contributing: CONTRIBUTING.md
          - Enterprise: https://jeweledtech.com/enterprise
        
        plugins:
          - search
          - mermaid2
        
        markdown_extensions:
          - pymdownx.highlight
          - pymdownx.superfences
          - pymdownx.tabbed
          - admonition
          - codehilite
        EOF
        fi
        
        mkdocs build
    
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./site